server:
  port: 8091

spring:
  datasource:
    url: jdbc:postgresql://postgres-container:5432/bootcamp_2508_final_project
    username: postgres
    password: admin1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  data.redis:
    host: ${SPRING_REDIS_HOST:redis-container}
    port: 6379

app:
  provider:
    base-url: http://data-provider-app:8090
    api-token: d1n3u8hr01qlvnp5dhv0d1n3u8hr01qlvnp5dhvg
  upload:
    dir: /uploads


